### ISSUE TITLE
Issue with 'path' node type

### ISSUE THREAD

**Issue by xogeny** [jsonata-js/jsonata#109]
This may be an issue with other node types too, but I noticed it with path when writing some evaluation code and I think I've seen at least two cases of it "in the wild".

In the evaluation code, you have the following code:

```javascript
            if(ii === 0 && step.consarray) {
                resultSequence = yield * evaluate(step, inputSequence, environment);
            } else {
                resultSequence = yield * evaluateStep(step, inputSequence, environment);
            }
```

Basically this is saying the when faced with a path, you should treat them as transformations of the `input` value (because `resultSequence` becomes `inputSequence` as you loop over this code) unless the first one is an array constructor.  In that case, you should set the result to the result of evaluating the array constructor.

It seems to me (and I could be totally wrong here), that this is actually a defect in the AST design.  The reason I use the word "defect" is because when I looked at this code I thought of other ways it could fail and I think I'm able to demonstrate at least two different ones.  But I can imagine an alternative way of designing the AST that could avoid this special handling (and the two failures I've seen).

The issue is with the implicit assumption in the `path` type that the current context value as the initial value for all each `step`.  The array constructor breaks this because it defines an entirely new context.  But the problem I see is...*it isn't alone*.

Consider, for example, evaluating this:

`[{"size": 1}, {"size": 2}].size`

From this we get `[1, 2]`.  However, wrapping our array construction in a `block` using parentheses, *i.e.,*

`([{"size": 1}, {"size": 2}]).size`

Now gives us this: `[1,2,1,2,1,2]`. **???** (even though if we drop the `.size` from both expressions, we get exactly the same answer).

Note it isn't just `block` nodes either.  I suspect a function evaluation could trigger the same issue in some circumstances.  I suspect there are other cases as well.

It seems to me that a clean way to address this would be to have an explicit `head` AST node associated with each `path` node.  This `head` node would represent the initial value in the loop over the steps and in most cases, its value would be the equivalent of `$` (the current context).  But the key thing here is that the **parser** could determine this not the evaluator.  I don't know for certain because I'm not that familiar with the grammar, but my guess is that the parser can determine unambiguously what the "head" of the expression is and encode that in the AST so that we don't need to worry about these special cases while tree-walking.

Or am I completely off base here?  In any case, I think there is a bug here (see my examples above).  My point is that I think this can be addressed cleanly at the AST level.

**Comment by xogeny** [comment]
Looking into this a bit more, it seems as though `path` is not really part of the AST generated by the parser, but rather something that results from post-processing of the AST.  It isn't really clear to me what `path` is meant to represent or how it is different from `block`.  I'll continue to look into it, but if anybody has an explanation they can provide, that would be useful.

**Comment by andrew-coleman** [comment]
A `path` represents a sequence of steps separated by a `.` operator.  It has similar semantics to a [relative path expression in XPath](https://www.w3.org/TR/xpath-31/#doc-xpath31-RelativePathExpr).  Due to the nature of the parsing algorithm, I'm not able to capture a `path` in the AST during the parse phase.  But it's really useful in the evaluation engine to be able to iterate over an array of steps rather than having to navigate a tree structure containing the steps.  Hence I flatten the steps into a `path` node in the post-parse stage (as well as other stuff like tail-call elimination).

It's different from a `block`.  A `block` is simply a sequence of expressions that get evaluated in order, with the result of the final expression becoming the result of the block as a whole.  Each expression within the block is evaluated in the same `context`.  A `block` represents an environment scope, in other words any variable bound within a block will go out of scope when the block closes.  A block can also be used override operator precedence (usual use of parentheses). 

A `path`, on the other hand, represents a set of `map` operations (in the functional programming sense).  So each step in the path is evaluated in the context of each item in the sequence of the previous step, then combined and flattened into a resultant sequence (array).  This is taken from XPath, and is probably explained much better in the XPath spec.

**Comment by xogeny** [comment]
OK, this all makes sense.  And the example I gave of `([{"size": 1}, {"size": 2}]).size` returning `[1,2,1,2,1,2]` is fixed after the merge of `singleton`.  So I'll close this.  I'm still concerned about #121 and its potential relationship to this.  But since that is opened as a separate issue, there is no need to keep this open.
