### ISSUE TITLE
EBNF Grammar?

### ISSUE THREAD

**Issue by xogeny** [jsonata-js/jsonata#116]
I see, from looking at the code, that Pratt's algorithm is being used for constructing the AST.  But one downside is that I don't see any EBNF-like grammar here so it is hard to really understand the grammar rules.

Now I'm guessing that since you are using Pratt's algorithm, the operators are central to the parsing and perhaps that doesn't map well onto EBNF.  But it would still be useful to understand how to form a grammatically correct expression.

Am I missing something?

**Comment by andrew-coleman** [comment]
Pratt's algorithm builds the AST based on the relative precedence of each operator.  The table of operator precedences is at the top of the jsonata.js file.  The reason I took this approach is because it allowed me to rapidly prototype the language in its early days, experiment with operator precedence and add new operators without having to rewrite a grammar.  

The language is now mature enough where it is appropriate (and probably desirable) to write an EBNF, but I have not attempted to do this yet.  @tomklapiscak, how are you dealing with this in your Java implementation?

**Comment by xogeny** [comment]
I'm not sure using an EBNF parser generator will add that much.  You'd have to use one that didn't bundle a runtime (or else you'd add a dependency) and I suspect the generated code would be much bigger which could increase bundle size.  It seems you've gotten pretty far just building the tree from operators so I'm not convinced that part should change.  I just thought an EBNF grammar would be good for conveying the grammar to humans.

I'm still investigating the parser code.  One complication is the second pass you make to optimize the AST.  I'm not quite sure what, for example, what `path` is doing there.  It it just a flattening of binary operations...or does it represent something else?

**Comment by xogeny** [comment]
Looking at the parser further, I suspect you might actually be able to generate the EBNF automatically *from* the parser symbol table.  I'm going to close this for now, but I suspect if anybody wants to generate EBNF you could probably do it by leverage the operator precedence defined in the parser and a package like [this one](https://github.com/tabatkins/railroad-diagrams) to make some very nice documentation.

Maybe I'll even take this on in the future.  But I've got some bigger fish to fry first.
