### ISSUE TITLE
Minimum Node version for development

### ISSUE THREAD

**Issue by xogeny** [jsonata-js/jsonata#125]
I see that this project includes a `package-lock.json` file.  That file is meant to work with `npm` version 5.x.x which only comes with Node 8.x.  *So*, can we assume Node 8 as the development platform? (`package.json` says Node>=4)

Keep in mind, I'm not proposing that we discontinue support for ES5.  That is a separate issue.  Just whether we can assume Node 8.x for development work.

Comments?

**Comment by mattbaileyuk** [comment]
I think that got left behind and accidentally checked in when @andrew-coleman was running Node 8.x locally; the intention is to continue to support Node 4.x at least until popular consumers like `node-red` up their minimum level (might happen after 4 drops off maintenance at the end of April).

Are you asking about Node 8.x as the development environment because you want to take advantage of newer features in node?

**Comment by xogeny** [comment]
I was asking for two reasons.  First, because in order to take advantage of `package-lock.json` and getting reproducibility of development environments, you'd need `npm` 5.x.x.  But also because support for `async`/`await` would be super nice to have (and presumably compiled away by Babel for deployment to browsers).  But that only showed up in 7.6.x.

All *that* being said, if it were up to me (and I fully acknowledge that it *isn't*), I would move from using `babel` to TypeScript.  You'd get all the transpilation benefits (*i.e.,* you could still transpile to es5), all the really nice language features (es6 imports, async/await, etc) and, best of all, static type checking of all the data (tokens, symbols, AST nodes) being passed around and, as a result of those checks, I suspect we'd uncover lots of edge cases (like in #115 and what I suspect is behind #121).  In that case, the discussion about Node version would be less important because the language features wouldn't depend on it, only the libraries.  I already created a basic `jsonata` evaluator package in TypeScript for another project.

**Comment by mattbaileyuk** [comment]
I suspect it was for `async`/`await` as that's the same reason another project I'm on is trying to push up to `8.x`. I agree in theory Babel covers us here so that `jsonata-es5.js` will come out nice and ready for things like `node-red` which use it, browsers directly, etc. But I haven't had a chance to give it a go to be able to say that with confidence.

**Comment by andrew-coleman** [comment]
Support for node v4 has been dropped.
The library gets tested on versions 6, 8, 10 & 11.  The 'deploy to npm' stage gets done using v10 only.
