### ISSUE TITLE
Array indexing with input document value fails

### ISSUE THREAD

**Issue by DeanCording** [jsonata-js/jsonata#143]
I have the following input document:
```
{
 "topic": "emontx",
 "payload": {"circuit":4,
             "realPower":0.03,
             "apparentPower":2.77,
             "powerFactor":0.01,
             "Vrms":244.96,
             "Irms":0.01,
             "freq":49.85}
}
```
and I need to map the circuit value to a meaningful name.  Here is some jsonata code that should do it:
```
(
    $circuits := ["", "solar", "grid", "lights", "hotWater"];
    $circuitNo := payload.circuit;
    $circuit1 := $circuits[payload.circuit];
    $circuit5 := $circuits[$circuitNo];
    $circuitFixed:= $circuits[4];

    {  "circuitNo1": payload.circuit,
       "circuitNo2": $circuitNo,
       "circuits": $circuits,
       "circuit1": $circuit1,
       "circuit2": $circuits[payload.circuit],
       "circuit3": $circuits[$number(payload.circuit)],
       "circuit4": $circuits[$circuitNo],
       "circuit5": $circuit5,
       "circuitFixed1": $circuitFixed
   }
)
```
so circuit1, circuit2, circuit3, circuit4, and circuit5 should all have the value 'hotWater'.  But the output I get is:

```
{
  "circuitNo1": 4,
  "circuitNo2": 4,
  "circuits": [
    "",
    "solar",
    "grid",
    "lights",
    "hotWater"
  ],
  "circuit4": "hotWater",
  "circuit5": "hotWater",
  "circuitFixed1": "hotWater"
}
```
Only circuit4 and circuit5 worked. 

circuit1, circuit2, and circuit3, which directly use payload.circuit as the index do not return anything.  Even wrapping payload.circuit in a $number function does not do anything.

**Comment by shrickus** [comment]
Hi Dean-

This revised expression does what you would expect:
```
(
  $circuits := ["", "solar", "grid", "lights", "hotWater"];
  $circuitNo := payload.circuit;
  $circuit1 := $circuits[$$.payload.circuit];
  $circuit5 := $circuits[$circuitNo];
  $circuitFixed:= $circuits[4];
  {
    "circuitNo1": payload.circuit,
    "circuitNo2": $circuitNo,
    "circuits": $circuits,
    "circuit1": $circuit1,
    "circuit2": $circuits[$$.payload.circuit],
    "circuit3": $circuits[$number($$.payload.circuit)],
    "circuit4": $circuits[$circuitNo],
    "circuit5": $circuit5,
    "circuitFixed1": $circuitFixed
  }
)
```

It has to do with the current "context" that jsonata uses to evaluate the bare word `payload` -- which holds the node-red `msg.payload` value that is passed into the node.

Notice that in the second line, the payload object is correctly able to retrieve the circuit number:
`$circuitNo := payload.circuit;`
since the context is already the root of the incoming data, which in jsonata terms is `$$`
(btw, a single bare `$` is shorthand for the current context).

But if that same expression is put inside the brackets, it is relative to the `$circuits` array  that is currently being evaluated. So any time your expression needs to reference the root of the incoming msg, you need to use the double dollars sign prefix -- in fact, it's more precise to say that the only time you **don't** have to use `$$.payload` is at the outside edges of the evaluator... which is normally at the start of your expression.

There is a short section that discusses "Built-In Variables" on this [documentation page](http://docs.jsonata.org/programming.html).

**Comment by DeanCording** [comment]
Thanks Steve,

Whilst I understand what you are saying, it is very counter-intuitive - particularly as it doesn't match the scope that $variables have.   However, I can see the benefit of this approach as it allows you to use $variables as placemarkers to sections inside the input JSON, and it then makes sense to be able to apply selectors just as you would for the actual input JSON.  In fact, $variables are essentially all just pointers to JSON objects.  Useful stuff but it requires a bit of mental gymnastics to come to grips with.

The documentation says:
> $$ The root of the input JSON. Only needed if you need to break out of the current context to temporarily navigate down a different path. E.g. for cross-referencing or joining data. 
which does imply that it's use is an exceptional case. (and yes, what I was doing was cross-referencing).

I have a re-read of the documentation and I think it would help if it explained how path, context, blocks, scope, selectors and variables worked together in a bit more detail.  A lot of the information is there but scattered about in different sections which makes it difficult to get a good initial understanding of the underlying concept.

 Dean

**Comment by andrew-coleman** [comment]
Closing as I believe this has been answered.  Thanks for the feedback on documentation.
