### ISSUE TITLE
Configurable date formats and time zones

### ISSUE THREAD

**Issue by deepilla** [jsonata-js/jsonata#166]
The Go implementation of JSONata is extending the date functions to allow user-defined date formats and time zones. We think this would be a useful addition to the JSONata standard so I'm opening this issue as a request for comment.

The relevant functions are:

    $now()  // returns the current time as a string

    $fromMillis(number)  // converts a Unix time to a string
    
    $toMillis(timestamp)  // converts a string to a Unix time

All of these functions use ISO 8601 date format and UTC. We plan to add the following optional arguments:

    $now([picture [, timezone]])
    
    $fromMillis(number [, picture [, timezone]])
    
    $toMillis(timestamp [, picture])

The `picture` argument specifies a date format using a subset of [XPath's date/time syntax](https://www.w3.org/TR/xpath-functions-31/#date-time-examples). The `timezone` argument specifies the time zone to use when outputting a date as a string. It should handle IANA identifiers like "America/Chicago", time zone abbreviations like "EST", and explicit time offsets like "-0500".

To ensure backwards compatibility, the new arguments will be optional with defaults that make existing expressions generate the same results as before.

**Comment by andrew-coleman** [comment]
+1

I like the fact that it is aligned with XPath's picture syntax which has a very well defined semantic for formatting.  We need to give some thought as to how this picture syntax is applied to *parsing* in the toMillis() function, since XPath does not define that.

**Comment by deepilla** [comment]
FYI, here's what I've implemented in jsonata-go. Everything is basically per [the docs](https://www.w3.org/TR/xpath-functions-31/#rules-for-datetime-formatting) but there are a few simplifications.

- We only support the Gregorian calendar. The [C] and [E] date formats (Calendar and Era) return the fixed values "AD" and "Christian Era" respectively.

- We only support English (for now). We could add other languages in the future.

- When formatting numbers, only numeric layouts are permitted. We don't support string formats like Roman numerals and words (e.g. "two thousand and eighteen"). This allows us to reuse the `formatNumber` function (and greatly simplifies internationalisation).

- The default picture string is `"[Y]-[M01]-[D01]T[H01]:[m]:[s].[f001][Z01:01t]"` and the default timezone is UTC. This matches the current jsonata-js behaviour.

- Sunday is the first day of the week.

- When parsing, values that are not defined in the input string are assumed to be 0 (or 1 if that doesn't make sense).

**Comment by andrew-coleman** [comment]
@deepilla sorry I've been so quiet on this for so long.  I've created a [branch](https://github.com/jsonata-js/jsonata/tree/date_time) with a reasonably complete implementation of the XPath fn:format-dateTime and fn:format-integer functions together with associated parse functions that work with the same picture strings.

I planned to add them to JSONata via the toMillis/fromMillis functions as you suggested above, however, I hit a problem with the `toMillis(timestamp [, picture])` idea.  Currently, `toMillis(timestamp)` is declared to have a single string parameter which, if absent, will use the context value as the first param (i.e. the signature is `<s-:n>`).   If I was to extend this with a second, optional, string parameter, then I think there would be an ambiguity.  If the user was to call this function with a single string parameter, should it interpret this as the `timestamp` (and ignore the context), or should it interpret this as the `timezone` and use the context as the first param?   How do you deal with this in your implementation?

Currently, I've added these in as new functions `$formatDateTime(millis, picture [, timezone])` and `$parseDateTime(timestamp, picture)`.  I've also added `$parseInteger(valueStr, picture)` and `$formatInteger(number, picture)` simply because they are used by the date/time formatting/parsing functions and I thought they might be useful standalone (as XPath does too).

I'm keen to keep our implementations in step, so I'd be interested to hear your thoughts on this.

**Comment by deepilla** [comment]
The jsonata-go version of toMillis only uses the context if it is called with no arguments. When called with a single argument, that argument is assumed to be the timestamp. Basically the behaviour is unchanged in that regard so as not to break existing expressions.

I'm not quite sold on the new date functions. This strikes me as a textbook case for default arguments and I think they make for a more consistent, less confusing API. It'd be a relatively minor change though I guess.

**Comment by andrew-coleman** [comment]
I certainly _could_ arrange for it to behave that way. My concern is that the following expression would work as expected:

`[1e11, 1e12] . $fromMillis('[D]/[M]/[Y]') `

because it can distinguish the numeric context value from the optional string arg2. But this one would fail:

`['21/10/2018', '31/05/2000'] . $toMillis('[D]/[M]/[Y]')`

because the `'[D]/[M]/[Y]'` string arg will be assumed to be arg1.

Looking through the list of existing functions, I notice that `$round` and `$formatBase` also exhibit this same quirk, and nobody has complained so far.  So if you are still happy with this, and no one else shouts (fairly quickly), then I'll change my implementation to match yours.

**Comment by deepilla** [comment]
I'm fine with that. I suspect that this will also turn out to be a non-issue in practice. And if anyone really needs an expression like your second example, the context can be explicitly provided like this:

```
[3.14159, 1.2345] . $round($, 2)  // returns [3.14, 1.23]
```

This might be worth revisiting in the future (e.g. for jsonata v2). You run into the same issue whenever you have a context argument followed by an optional argument of the same type. But I don't think that's reason enough to not have those functions where it makes sense.
