### ISSUE TITLE
proposal: regex =~ operator for boolean expressions

### ISSUE THREAD

**Issue by michaelthoward** [jsonata-js/jsonata#190]
I propose adding =~ and !~ as boolean regex match operators to be used primarily for testing strings in predicates. 

I wanted to perform a regex match as part of a predicate and that syntax came naturally to me ... even though it has been a long time since I've done any perl programming. 

http://try.jsonata.org/ryzUc7Usf demonstrates using the existing $match() function. 

http://try.jsonata.org/HkpWXV8sM demonstrates using the chain operator ~> but $match is still explicitly required 

With the proposed =~ operator the predicate in this
`Account.Order.Product[$match($.`Product Name`, /hat/i)].SKU`
or
`Account.Order.Product[`Product Name` ~> $match(/hat/i)].SKU`
would become 
`Account.Order.Product[`Product Name` =~ /hat/i].SKU`

_(note: markdown conflict with backticks)_

My initial thought was that =~ should just be an alternate syntax for the existing $match() function ... along the lines of ~>

I then switched to thinking that it would present a simpler user-model if these were treated as operators which returned boolean values.

**Comment by deepilla** [comment]
You're in luck! This syntax already exists, it's just not documented. To get the items matching a regex, use an expression like this:

```
Account.Order.Product[`Product Name` ~> /hat/i].SKU
```

For non-matching items, use `$not()`:

```
Account.Order.Product[$not(`Product Name` ~> /hat/i)].SKU
```

This works because regular expressions in JSONata are functions that take a string and return the matches in that string (or `undefined` if there are no matches). See [this closed issue](https://github.com/jsonata-js/jsonata/issues/177) for more background. There's also [an open issue](https://github.com/jsonata-js/jsonata/issues/183) to have this functionality included in the docs.

**Comment by michaelthoward** [comment]
Excellent. Thanks very much for responding. 
> regular expressions in JSONata are functions that take a string

Got it. 

I will leave this ticket open and let someone in authority close it as they see fit.

**Comment by andrew-coleman** [comment]
Thanks @deepilla for answering.  Closing as resolved.
