### ISSUE TITLE
What is the purpose of the $clone() function?

### ISSUE THREAD

**Issue by deepilla** [jsonata-js/jsonata#193]
In jsonata-js, there is an undocumented `$clone()` function which creates a deep copy of an object. When you use the object transform operator, JSONata uses this function to make a copy of the original object. More accurately, JSONata looks up the value of the `$clone` variable and uses whatever it finds. This allows users to control the deep copy semantics by providing their own `$clone()` function. I believe this backdoor was added for node-red.

I don't know much about node-red but I understand that it's built on nodejs and is therefore JavaScript only. So I have not added the backdoor to jsonata-go. But now I'm wondering whether I need to expose the `$clone()` function at all. Are there any other uses for it? I can't think of a situation where an end-user would need it.

**Comment by xogeny** [comment]
IIRC, I have found cases, in implementing the evaluation semantics, where some objects are mutated.  So a `$clone` function could also be a hedge against mutation side effects.  Personally, I'd like to refactor the code so that this mutation involves a deep copy to avoid any weird side effects.

My point is that I could imagine the function is there to allow users to insulate themselves against such side effects.  But my proposal would be to avoid the need for such a function by using completely immutable data everywhere.  But that is outside the scope of your immediate question I suspect.

**Comment by deepilla** [comment]
I don't think JSONata is supposed to have side effects. At least that's the impression I got from [this discussion](https://github.com/jsonata-js/jsonata/issues/70) about manipulating JSON. So if you're seeing objects being mutated, that's probably a bug (like [this issue](https://github.com/jsonata-js/jsonata/issues/139)). This is why I'm querying the need for a `$clone()` function (absent the node-red requirement).

**Comment by xogeny** [comment]
Well you are correct in that the `clone` function [is used](https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L2514) to make a copy of some data before applying the mutations.  But I think it is still possible for a malicious function to perform mutations.  But I think it is sufficient to simply state that they shouldn't (vs. somehow preventing them).

**Comment by michaelthoward** [comment]
My thoughts ...

JSONata is intended to be a functional query language. Therefore any mutation of data structures would be a bug. If you are living in an immutable world then a `$clone()` operation does not have any purpose ... because nothing can be mutated. 

> In jsonata-js, there is an undocumented $clone() function which creates a deep copy of an object. 

[This discussion thread](https://github.com/jsonata-js/jsonata/issues/70) referenced by @deepilla talks about a prototype JSONata Update Facility which explicitly updates data structures. In this context I would think that `clone()` would be requirement. 

*** some time later ***

I took a look at the jsonata source. There were no references to `clone` in older jsonata-1.1.1.js but there are references to `clone` in the current source. Looks to me like as part of `evaluateTransformExpression()`. This is consistent with comments by @andrew-coleman in the [aforementioned thread](https://github.com/jsonata-js/jsonata/issues/70). 

I conclude that the _undocumented $clone() function_ is part of the undocumented JSONata Update Facility referred to in the [aforementioned thread](https://github.com/jsonata-js/jsonata/issues/70).

**Comment by andrew-coleman** [comment]
As discussed above, `$clone` never need be called within a JSONata expression because of its functional nature.  It was added in order to allow the implementation's deep-copy function to be pluggable.  It is only used in an object transform expression (`|...|...|`) and was requested by Node-RED to allow them to plug in their own deep-copy implementation (see discussion [here](https://github.com/jsonata-js/jsonata/issues/70#issuecomment-326591114))
