### ISSUE TITLE
Combining the results of predicates

### ISSUE THREAD

**Issue by kazoompa** [jsonata-js/jsonata#203]
Hi,

I was wondering whether there was a way of combining the result of two predicates:
`**.Product.Description[Weight<0.6 and Weight>0.6]
`

The following results in a boolean value as documented:
`**.Product.Description[Weight<0.6] and **.Product.Description[Weight>0.6]
`
This is the closest I got to my need but not too adequate:
`[[**.Product.Description[Weight<0.6]],[**.Product.Description[Weight>0.6]]]`

Which yields this:
```
[
  [],
  [
    {
      "Colour": "PURPLE",
      "Width": 300,
      "Height": 200,
      "Depth": 210,
      "Weight": 0.75
    },
    {
      "Colour": "Purple",
      "Width": 300,
      "Height": 200,
      "Depth": 210,
      "Weight": 0.75
    },
    {
      "Colour": "Black",
      "Width": 30,
      "Height": 20,
      "Depth": 210,
      "Weight": 2
    }
  ]
]
```

Thanks,

**Comment by michaelthoward** [comment]
Unclear to me exactly what you are asking. 

My initial thought when looking at 
`**.Product.Description[Weight<0.6 and Weight>0.6]`
is that you have confused the boolean behavior of 'and' with 'or'. 
As you have listed, the result should be the empty set ... you cannot have `Weight<0.6` while at the same time have `Weight>0.6`. It looks to me like the results at http://try.jsonata.org/rkax-Ym2G are exactly correct. 

http://try.jsonata.org/H15EFuXhG shows the query using or ... where nodes with Weight < 0.6 or Weight > 0.6 are included. This includes everything except where Weight = 0.6


http://try.jsonata.org/BJYvduQ2z shows the query using or ... with the value changed from 0.6 to 0.75 to better demonstrate the effect of the or operation ... since the Weight values themselves are 0.6, 0.75, 0.75, 2

If that is not what you are asking, then please clarify.

**Comment by kazoompa** [comment]
Hi Michael,

You are right, my mistake! Thank you for the response, hell of a library, I find it much more useful than JSONPath for JS.

Best,
