### ISSUE TITLE
[N] (access array element by index) operator is ignored in chaining expressions

### ISSUE THREAD

**Issue by eschava** [jsonata-js/jsonata#212]
Example:

Data: "test"

Expression $ ~> $split('e') produces ["t", "st"] (correct)
Expression $ ~> $split('e')[0] produces ["t", "st"] as well
Expression $ ~> $split('e')[bla-bla] also produces ["t", "st"]

I expect the second expression will produce string "t" and the third expression will lead to compilation error

**Comment by xogeny** [comment]
The issue here is order of operation.  What you want is:

```
($ ~> $split('3'))[0]
```

**Comment by eschava** [comment]
Thank you 
But when that [] operator is applied?
Also, it would be cool allow it as a part of a chained expression, smth like
$ ~> $split('e') ~> [0]

**Comment by xogeny** [comment]
Well, consider the following slightly rewritten version of your example:

```
($a := function ($x) { $split($x, "e") }; $ ~> $a)
```

In this case, `$a` is a function to be evaluated and `~>` is triggering it.  But your `[0]` was effectively be associated with the function **not its result**.  So you were doing something like this:

```
($a := function ($x) { $split($x, "e") }; $ ~> $a[0])
```

...and my fix was to make it:

```
($a := function ($x) { $split($x, "e") }; ($ ~> $a)[0])
```

You might say "but `$a` isn't an array, what does it mean to apply `[0]` to it?".  Well, in jsonata everything can be treated as if it were an array, even if it isn't.  So applying `[0]` to a scalar just gives you back the scalar (which in this case was your function).

Keep in mind that there are some subtle things going on here because `$split("e")` is actually a function, not a function invocation (because it is still missing one argument).

I hope that helps.

**Comment by eschava** [comment]
Wow. It was like dipping head into boiling water :)
Thanks a lot! Now it looks clear

**Comment by xogeny** [comment]
If this answers your question, can you mark the issue as closed?  Thanks.
