### ISSUE TITLE
Object Construction Syntax

### ISSUE THREAD

**Issue by xogeny** [jsonata-js/jsonata#215]
### Introduction

There are two aspects of object construction syntax that I think could be improved.  I thought it would be good to start a discussion of those issues here and see whether that leads us to a consensus.  Both issues are related to differences between JSONata and JavaScript notation.

### Expressions for Keys

The first issue is with the use of literals vs. expressions as keys.  In JavaScript, you can build an object with a literal key using the syntax `{ "name": name }`.  In this case, `"name"` is a string literal key and `name` is a variable whose value will be used as the value associated with the key.

Now circumstances arise (in JavaScript) where you may want to have the key specified by a variable or expression.  In that case, you can use the following syntax: `{ [nameKey]: name }`.

In JSONata, we have the same needs.  When you want the key to be a known string literal, the syntax is the same, *i.e.,* `{ "name": name }`.  But when you want to use an expression as the key, you would write `{ nameKey: name }`.  It would be more intuitive if we could align the two syntaxes so that in JSONata we also used `{ [nameKey]: name }`.  I suspect making the "this is an expression" syntax more explicit is better for catching user errors as well (*i.e.,* force the user to either surround the key with `"..."` or `[...]` to explicitly indicate how to treat the key).

### Shorthand

In ES6, JavaScript (not JSON) features a "shorthand" notation for object construction.  So instead of writing `{ "name": name }`, one can simply write `{ name }`.  In JSONata, I frequently find myself "extracting" a subset of properties and it often follows the pattern of `{ "name": name, "age": age, "phone": phone }`.  Note the repetition.  We could have a similar shorthand in JSONata for cases where the key is implied when only a *name* (and I mean this in the JSONata AST sense) is given for a field, *e.g.,* `{ name, age, phone }`.  JSONata syntax is, in general, quite dense (you can accomplish a lot with few characters).  But this is one case where more could be done in that direction.

My feeling here is that this wouldn't even need to touch the evaluator, it could be done completely in the parser by recognizing cases where only a name was given for a given field and then elaborating that into a string literal/expression pair.

### Conclusion

In both cases, we are making changes to JSONata that would align it more with ES6 constructs in JavaScript which, in turn, would be more intuitive to users.  When JSONata was developed, ES6 was not really finalized.  So it is understandable that a different syntax was employed.  But now that it is standardized, it seems like we should conform to JavaScript conventions so as not to confuse users.  Also note that we are not adding any new semantics to the language here.  All these operations already exist in JSONata.  We are just aligning them more to ES6.

**Comment by deepilla** [comment]
I'm not sure I agree with the premise that making JSONata more like ES6 would be more intuitive, or better in any sense really (except for JavaScript developers). As I understand it, JSONata is a tool that happens to have been written in JavaScript but, like JSON itself, is supposed to be general purpose. Just as there are implementations of the JSON spec in multiple languages, there could one day be multiple implementations of JSONata (I've been working on a Go port for example).

On that basis, there's no intrinsic advantage in aligning JSONata with ES6. Especially if it clashes with JSON, the one technology common to all JSONata implementations (e.g. giving `"..."` and `[...]` different meanings). I'm all for reviewing the syntax but I don't think that consistency with JavaScript should be the goal.

**Comment by xogeny** [comment]
@deepilla Let me turn this around.  Let's ignore, for the moment, any discussion of Javascript.

In the case of expressions for keys, I would argue that there is a problem with the current syntax in that it doesn't force you to explicitly indicate which semantics you (literal or expression for the key).  I've tripped over this multiple times.

In the case of shorthand notation, I would argue again that there is a problem with the current syntax in that it is unnecessarily verbose in many cases.  Again, I've run into that multiple times.

So perhaps we should start with...who agrees these are problems and who doesn't.  If nobody considers them problems then the entire ES6 dimension goes away.

**Comment by deepilla** [comment]
I don't quite understand the first point. If the key is a string it'll be in quotes and if it's an expression it won't be in quotes. What's to trip over?

**Comment by xogeny** [comment]
If you forget the quotes, it implicitly assumes it is an expression.  By forcing the user to enter `"..."` or `[...]` there is no implicit fallback.  You have to explicitly indicate whether you want a literal or an expression.

Now I recognize that JSONata isn't exclusively for Javascript (and that is a valid point), but the current implicit convention in JSONata is exactly the opposite of Javascript which is confusing.  In Javascript, if you leave the quotes off, it assumes it is a literal and not an expression. In JSONata, if you leave the quotes off it assumes it is an expression and not a literal.

So while I don't want to be overly favorable to Javascript, it is worth pointing out that all other things being equal (which they aren't), this really violates the principle of least surprise.

**Comment by deepilla** [comment]
Hmm... I don't find this confusing or surprising but then I don't write a lot of JS either. I would, on the other hand, think this syntax odd: `{ [nameKey]: name }`. Apart from the re-use of the array constructor, I'd be wondering why I needed brackets around the key but not the value (which could also be a string or an expression).

**Comment by michaelthoward** [comment]
I'm not a JavaScript/ES programmer. 
I'm in alignment with comments from @deepilla

> who agrees these are problems and who doesn't

I don't think it's a problem.

**Comment by andrew-coleman** [comment]
Thanks for raising this.  I intentionally let this sit for a few weeks in order to gather some discussion before weighing in.  Just to set the scene, JSONata is not Javascript and never set out to align syntax or semantics with Javascript.  It just happens that I implemented it in Javascript.  So this proposal should be considered on its own merit rather than consistency with Javascript.

As I see it, there are two separate proposals here:
1. Change to the syntax such that unquoted keys in the object constructor are always treated as string literals, and key names derived from an expression are embedded within square brackets (which is also the array constructor syntax in JSON).  This is a **breaking change** that would affect any existing expression that builds a JSON object.  
2. Allow key/value pairs to be specified by including just the value expression and deriving the key name by treating the expression as a string literal.  This could be implemented without breaking existing behaviour.  

For proposal 1, I agree with @deepilla.  I don’t find the ES6 syntax intuitive in this regard.  It seems to me that this `[…]` syntax was chosen as a way to get derived keys into javascript without breaking its existing syntax.  It doesn’t fit well with pure JSON which has different ideas about the meaning of `[…]`, as well as many other languages.

For proposal 2, I am slightly more sympathetic, although it might be of limited value.  In a realistic transformation scenario, I wonder how common it would be for the property name to coincidently be the same as the expression that generates its value.  Also, what would the property name be if the expression was non-trivial? (e.g. `foo.bar`, `price * 2`, `$substring(…)`, etc).

Although I could be tempted to close this with no action, I’ll let this sit a bit longer in case anyone else wants to express an opinion.  I’m not looking to count votes but I’m happy to have a well reasoned debate.

**Comment by jhorbulyk** [comment]
I agree with @andrew-coleman's assesment that there are two separate proposals here.  I agree with his assesment of proposal two.  For problem articulated by `Expressions for Keys`, I would propose the following changes (instead of the proposal articulated by @andrew-coleman):
* Have the interpreter recognize expressions of the form `{ [nameKey]: name }` as proposed
* Add the concept a strict-ness flag (or flags) to the interpreter/parser.  By default, this flag should be set to non-strict in which would see unquoted keys in object construction handled as per the current behavoir.  However, when this flag is set, the interpreter/parser should raise a syntax error when provided JSONata expressions in which keys are not wrapped in `" "` or `[ ]`.

The benefits are as follows:
* There are no breaking changes
* When this flag is set, it allows JSONata users to force syntax errors which are relatively easy to solve in order to prevent potential future logic errors which potentially are difficult to solve.

**Comment by xogeny** [comment]
A few comments.  First, for option 1, my point wasn't that unquoted strings should be treated as string literals.  Quite the opposite.  My position was that unquoted expressions should be errors.  This would force users to either user `[...]` or `"..."` and be *explicit* about how they wanted the keys evaluated (either as expressions or as strings, respectively).

Second, it seems like this is quite a controversial topic and, frankly, I'm just not interested in arguing in favor of such a thing.  My goal was never to try and impose Javascript aesthetics on everybody.  I only invoked Javascript because it has exactly the same issue (literals vs. expressions).  My point was that the current semantics regarding keys in object construction didn't seem to align with any language really (?) and, at least for me, this caused me to frequently create expressions that worked...just not as I expected.  So I was thinking if we were going to try and come up with a syntax it should a) avoid confusion (see paragraph above) and b) might as well try and solve the problem the way some existing language does (n'importe quelle langue).  I regard a) more important than b) since I don't really care about the syntax as much as I care about accidentally creating expressions that are valid and evaluate but don't do what I would otherwise intuit.

But in the end, it seems pretty clear that I'm in the minority here and that is perfectly fine.  I certainly don't want to impose any pain on anybody to "solve" an issue that people don't really think is a problem.
