### ISSUE TITLE
JSON filter not working as expected?

### ISSUE THREAD

**Issue by RobNiessen** [jsonata-js/jsonata#254]
{"tokenlist" : payload.tokenlist[sessiontoken != payload.sessiontoken]}

it should filter and show all except 'token-y', but it's showing nothing.
if i use a string instead of a param then the  correct results are shown.
{"tokenlist" : payload.tokenlist[sessiontoken != "token-y"]}

any idea?

Thanks Rob

`{
    "id": "567476547654",
    "payload": {
        "sessiontoken": "token-y",
        "tokenlist": [
            {
                "sessiontoken": "token-x",
                "ip": "1234567890",
                "entityid": "entity 10",
                "username": "rob"
            },
            {
                "sessiontoken": "token-y",
                "ip": "0987654321",
                "entityid": "entity 11",
                "username": "rob"
            },
            {
                "sessiontoken": "token-z",
                "ip": "10299485756",
                "entityid": "entity 12",
                "username": "rob"
            },
            {
                "ip": "87.213.19.54",
                "entitiyid": "5b800c4a4ef9d87500013968",
                "username": "rob",
                "sessiontoken": "707d795b.6083f8"
            }
        ]
    }
}`

**Comment by jhorbulyk** [comment]
The expression you likely want is
`{"tokenlist" : payload.tokenlist[sessiontoken != $$.payload.sessiontoken]}`

The issue that within the `[ ]` segment is that both sides of the operand are scoped to the item in the array being evaluated.  You need to use the [$$ built-in variable](http://docs.jsonata.org/programming.html#built-in-variables) in order to have the right side of your expression select from the initial input.

**Comment by mattbaileyuk** [comment]
Great to hear it's working, @RobNiessen :) And thanks for helping out @jhorbulyk 

Sounds like this is resolved, so I'll close this. Please reopen if you think there is still an issue.
