### ISSUE TITLE
Function signature for $keys should be <o-:a<s>>

### ISSUE THREAD

**Issue by wnm3** [jsonata-js/jsonata#303]
The $keys function operates on an object passed or via context variable but its function signature claims it works with anything (<x-:a<s>>)

**Comment by andrew-coleman** [comment]
The keys function also works on arrays of object.  It recurses through nested arrays until it finds any objects, then lists their keys (property names).  It needs to be tolerant (while ignoring) other types it might find along the way.  For example, applying `$keys()` to the following json:
```
[
  {
    "key1": "value1"
  },
  {
    "key2": "value2"
  },
  [
    {
      "key3": "value3"
    }
  ],
  4,
  "value5"
]
```
will result in 
```
[
  "key1",
  "key2",
  "key3"
]
```
So the function signature is intentionally lax, leaving it to the function implementation to do the type checking, where it has the flexibility to ignore rather than throw errors.

**Comment by andrew-coleman** [comment]
Closing this issue since I believe it has been addressed in the comments.  Feel free to re-open if you believe there is a bug.
