### ISSUE TITLE
Website SSL certificates

### ISSUE THREAD

**Issue by doug-shontz** [jsonata-js/jsonata#391]
First off, absolutely love this library and give much thanks to the people supporting it and how much this has helped my team!  Although this isn't "code-related" I didn't know where else to note this.

Would you consider getting an SSL certificate for the main jsonata.org and try.jsonata.org?  The docs site works fine under SSL, but I get a warning in all browsers if I just go to the main link on the GitHub repo and the try subdomain doesn't even respond under SSL.  We have a few of our team members who are very security conscious (that's actually what we pay them for...) and I would hate this awesome library turn anyone away if for some reason they feel that is a detriment.

Thank you for your consideration and thanks again for such a great library!

**Comment by andrew-coleman** [comment]
Thanks for the feedback.  I plan to move the whole website onto github pages at some point.  This will give me https for free.

**Comment by andrew-coleman** [comment]
All of the sites now use https.
https://jsonata.org/
https://try.jsonata.org/
https://docs.jsonata.org/

The exerciser has been rewritten using React.  I've switched to Monaco for the editor component because I couldn't get CodeMirror to behave under React.  The only downside of this is that Monaco does not support mobile devices.

I've updated the DNS settings for this domain to point to the new sites.  This should propagate over the next 24 to 48 hours.
