### ISSUE TITLE
parse string that start with a number throws 'Syntax error'

### ISSUE THREAD

**Issue by ildella** [jsonata-js/jsonata#392]
I've found out that this is true: 
```
  expect(() => jsonata('1abc')).toThrow('Syntax error: "abc"')
```

Is this expected? I can successfully do:

```
  const input = {'1abc': 1}  
  expect(input['1abc']).toBe(1)
```

**Comment by andrew-coleman** [comment]
The expression you are trying to parse is `1abc`, which is not a string, the tokenizer starts parsing it as a number, then throws an error when it find non-numeric tokens.  If you want to treat it as property name, then you need to enclose it in backquotes because it starts with a number.
See http://try.jsonata.org/Bk_NX98pr

To invoke this from javascript, you need the following:

```javascript
const input = {'1abc': 1};
expect(jsonata('`1abc`').evaluate(input)).toBe(1);
```
