### ISSUE TITLE
How to specify field starting with '$' in Predicates

### ISSUE THREAD

**Issue by xuanyue202** [jsonata-js/jsonata#43]
```
let json2 = {
    a:[
        {$type:'aa', value:1},
        {$type:'aa', value:2},
        {$type:'bb', value:3},
    ]
}

let ret = jsonata("a[$type='aa'][]").evaluate(json2);
console.log(ret);
```

I am expecting [{$type:'aa', value:1}, {$type:'aa', value:2}]. But the result is undefined. How to write this? I have tried "a[\\$type='aa'][]" "a[\$type='aa'][]" "a['\$type'='aa'][]" "a['\\$type'='aa'][]", None of them actually works.

**Comment by andrew-coleman** [comment]
`a[$.'$type' = 'aa']` 
or 
`a[$.'$type' = 'aa'][]` 
will get you the answer you require.

You are right that you need to quote the `$type` property name because `$` is a reserved token.  However, quoting it in isolation will just make it a string literal.  If a string literal is a step in a location path (i.e. either side of a `.`), then it will get interpreted as a property name by the parser.  Adding the `$.` prefix will do this.

An alternative approach is to use the `$lookup` function, as follows:
`a[$lookup('$type') = 'aa']`
This is useful if you want to use an expression to calculate the property name at runtime.

**Comment by andrew-coleman** [comment]
closing issue
