### ISSUE TITLE
Some expressions return by reference vs expected value

### ISSUE THREAD

**Issue by CanyonCasa** [jsonata-js/jsonata#446]
Per nodejs version 12.15.0; jsonata version 1.8.2

API documentation for _expression.evaluate_ states...

> Run the compiled JSONata expression against object input and return the result as a **new object**.

This makes sense, since you wouldn't want to alter the input source by a simple query. However, some expressions appear to return an input object reference rather than the value or new object, which can lead to corruption of the input source. as demonstrated by the following code...

```javascript
/// jsonata_testcase.js example...

// example database...
let db = {
  "groups": [
    {
      "name": "author",
      "members": [ "token", "me" ]
    },
    {
      "name": "developer",
      "members": [ "me" ]
    }
  ],
    "users": [
    {
      "username": "token",
      "hash": "$2a$10$0Ps9i4blTqmtFNEt/l.PL.5V0YH93E0H9UVt6xb.JxF1lAtkORENG",
      "member": [ "author" ]
    },
    {
      "username": "me",
      "hash": "$2a$10$m5AtjFoXEfL98BT.Lw2/SOO0WDiVybostmviYuMIoqcHg4D4Szchi",
      "member": [ "developer", "author" ]
    },
  ]
};

// this expression returns by reference ...
let expr = "users[username='me']";

// alternate 'equivalent' expression that returns by value ...
//let expr = "users[username='me'].{'username':username,'hash':hash,'member':member}";

const jsonata = require('jsonata');

let me = jsonata(expr).evaluate(db);

console.log("me:",me);

delete me.hash; // change to "result" that changes the "source"

console.log("me w/o hash:",me);

let newMe = jsonata(expr).evaluate(db);

console.log("newMe:",newMe); // this should not be modified
console.log("db users me:",db.users[1]);  // nor should this be modified!

```

Switch between the two expressions to see different results for equivalent queries.

**Comment by andrew-coleman** [comment]
Yes, this happens because JSONata works directly on the Javascript object.  A workaround would be to take a deep copy of the object before invoking `evaluate()`.  I don't do this because it could seriously degrade the performance for simple queries on large objects.

**All I can say is that within a JSONata evaluation, the expression itself will not alter the input message.**

The other way you could break this is to write an extension function in Javascript that modifies the input.  When invoked from inside the expression, this would violate the 'pure function' rule.  I don't think there's much I can do about that other than tell the implementors not to do it.
