### ISSUE TITLE
Problems with $split 

### ISSUE THREAD

**Issue by cdtyyz** [jsonata-js/jsonata#471]
Try this on the Invoices JSON data
$split($string(Account.Order.Product.Price),".")
Here is what is returned ...
[
  "[34",
  "45,21",
  "67,34",
  "45,107",
  "99]"
]
Seriously? the first and last value have an open and close square bracket after the split? 
$split($string(Account.Order.Product.Price),".")[0]
And the others are comma separated?
$split($string(Account.Order.Product.Price),".")[1]
Ultimately was trying to remove the decimals from the prices and multiply by quantity and thought split would do the trick, but clearly, not working since $number($split($string(Account.Order.Product.Price),".")[0]) is not a number and neither is $number($split($string(Account.Order.Product.Price),".")[1]) . 
So need to understand what it happening or better yet, how best to solve this example using jsonata

**Comment by andrew-coleman** [comment]
> Seriously? the first and last value have an open and close square bracket after the split?

Yes, seriously.  Because `$string(Account.Order.Product.Price)` returns the stringified form of the JSON array 
`"[34.45,21.67,34.45,107.99]"` and you are splitting that.

If you want to stringify and split each price individually then apply the functions using the mapping operator:
`Account.Order.Product.Price.$string().$split('.')[0]` returns `[ "34", "21", "34", "107"]`

You'll need to cast the strings back to number if you want to multiply them by the Quantity;
`Account.Order.Product.(Price.$string().$split('.')[0].$number() * Quantity)`

I suggest you'd be better off using the `$floor` function for removing the decimals:
`Account.Order.Product.($floor(Price) * Quantity)`
