### ISSUE TITLE
Get parent key in transform?

### ISSUE THREAD

**Issue by emilefyon** [jsonata-js/jsonata#472]
First of all, thanks for building JSONata! It saved my day so much.

I am having a bit of an issue trying to get the key of the parent element.

Here is my JSONata exerciser link: https://try.jsonata.org/KoCRz2CgH

My expression works perfectly fine for my elements, but it does not seem to have the $key defined (see screenshot below):

![image](https://user-images.githubusercontent.com/122733/90322162-f93b1d00-df50-11ea-8238-c1cf017d9ca4.png)

Expected results should be {i18.marital_status.label}

Doing something wrong or is it buggy/not possible?

Thanks a lot!
Emile

**Comment by andrew-coleman** [comment]
Hi Emile, the reason your expression doesn't work is because the `$key` variable binding goes out of scope before you reference it.  Variables are scoped to the block they are defined in (https://docs.jsonata.org/programming#variable-binding).

I've modified your expression slightly which I hope gives you the result you wanted:
https://try.jsonata.org/tQpD4JxYV

**Comment by emilefyon** [comment]
Hello Andrew,

Sorry, I did not see your answer. Works like a charm! Thx a lot!

Emile
