### ISSUE TITLE
Convert Date without separators

### ISSUE THREAD

**Issue by laemmlem** [jsonata-js/jsonata#500]
Hi,

i was trying to convert a ISO date string without separators to a date with:
$toMillis('20130305', '[Y0001][M01][D01]') ~> $fromMillis('[Y0001]-[M01]-[D01]').

Result is: "1303-01-05"

But this doesn't work. Somebody have a clue?

Best
Michael

**Comment by markmelville** [comment]
I looked into the code. `toMillis` doesn't work for formats without literal delimiters (a space, a slash, a dash, etc.). In theory, it could be fixed by using the formats to specify how many digits each part should be. So, I'd call this a bug. At the very least a fix would be to throw an error that this format is not supported.

A workaround for that particular format would be to parse out the parts with `$substring`.

**Comment by laemmlem** [comment]
Workaround with `$subtring` works. Think should be implemted imho. My solution:

(
$date := incomingDate;
$substring($date,0,4) & "-" & $substring($date,4,2) & "-" & $substring($date,6,2)
)
