### ISSUE TITLE
Important thing missing to me in the documentation

### ISSUE THREAD

**Issue by aschaepper** [jsonata-js/jsonata#529]
Hello together

First of all I would like to thank you for this great project, I picked it up yesterday and its a pleasure to learn jsonata. The website is great, the website to try it out, documentation, samples, everything.

I went through the documentation first, tried it out etc and strugglet a bit. Then I found this video from Andrew Coleman on youtube: https://youtu.be/TDWf6R8aqDo At around minute 18:46, he explains something extremely important which I think is not really highlighted in the documentation.

He is actually writing json objects in the jsonata markup / transform language itself. I didnt think that this is allowed or even possible but when I saw this it immediately got me on track to solve my problem.

I was thinking more in terms of: I have json as input, the jsonata language to transform the input, resulting in another json output.
But the way jsonata works is more like you get the json as input, "on the fly" create json if you like, as well as transform it with jsonata, and get an output.

I think it would be great if this would be more highlighted in the documentation. I hope you know what I mean, am I clear enough?

But still, awesome project, thanks all of you guys!

**Comment by markmelville** [comment]
It seems to me that part of video demonstrates [Result Structures](WSpdx+CQWKSS) from the documentation. He wasn't writing JSON, because `{"date":day}` is not valid JSON. It's an object constructor with a string literal for key and an expression for a value. True, any valid JSON is a valid jsonata expression, but it's a static expression because it's composed of literals.

The introduction in the [Overview](https://docs.jsonata.org/overview) mentions to all major features of the language, but I can see how readers might gloss over this:
> results of queries can be formatted into any JSON output structure using familiar JSON object and array syntax.

**Comment by aschaepper** [comment]
Thanks for your reply, yes this is a tiny bit, but thanks for pointing it out!

Greeetings

Alex
