### ISSUE TITLE
Not work with long integer

### ISSUE THREAD

**Issue by yangyao** [jsonata-js/jsonata#543]
JSON:

```
{
  "id": 13760119210069
}
```

JSONATA
```
{
   "id":id
}
```

OUTPUT

```
{
  "id": 13760119210070
}
```

13760119210069 => 13760119210070 ?

**Comment by andrew-coleman** [comment]
In this implementation of JSONata, all numbers are represented using Javascript's Number type which is IEEE-754 floating point.  This puts a limit on precision to about 13 s.f. 

This is a limitation I'm afraid.

**Comment by sarumont** [comment]
@andrew-coleman We should be able to support between 15 and 17 digits, according to the IEEE spec (my assumption is the variable nature there is due to machine epsilon, but I haven't gotten deep enough to confirm or refute that). 

The [string function](https://github.com/jsonata-js/jsonata/blob/master/src/functions.js#L134) is specifying a precision of `15` which, given the 15-17 range, is safe...but it does expose what I would call a bug in JSONata: it omits JavaScript's  `Number.MAX_SAFE_INTEGER` (which is a number with 16 significant figures).

See [this snippet](https://try.jsonata.org/FX8mUQaj6) for an example of the behavior.

I would propose that your `isNumber` check should be updated to use `Number.isSafeInteger` rather than `Number.isFinite`. Making this check, the `toPrecision` call can be updated to use a precision of `16` and safely cover the JavaScript safe number space. See [this fiddle](https://jsfiddle.net/md8hopj5/) for some supporting documentation.
