### ISSUE TITLE
Nested "type" or "value" fields do not work as expected

### ISSUE THREAD

**Issue by RichardSylvester** [jsonata-js/jsonata#550]
When attempting to compare or use deeply nested fields with the names `type` or `value` and `**` the outcome is always false.

For example:  `**.value="GOOD" or **.type="String"` always equates to false even if these values exist

Additionally:
`metric.*.rating.value="GOOD"` works
`metric.*.*.value="GOOD"` does not work, however any other field name does work

The same is also true when used in functions such as:
`$contains($lowercase(metric.properties.rating.value), "good")` works
`$contains($lowercase(metric.properties.*.value), "good")` throws an error
`$contains($lowercase(**.value), "good")` throws an error

This is true for the fields `value` and `type`

See example here:  https://try.jsonata.org/JsuAl1lDA

**Comment by andrew-coleman** [comment]
That's because `type` and `value` appear multiple times in your document and your wildcard expressions are selecting all of them.  For example, `**.value` results in `[31, "Zone Air Humidity Sensor", "GOOD"]`, so when comparing it to `"GOOD"`, it will result in `false`.  You've given lots of examples, but it's not clear from your comment (is it a question?) what you are trying to achieve.

**Comment by RichardSylvester** [comment]
Thanks for your response Andrew.  I apologize, Friday was a long day, lots of hours, evaluating a couple of similar libraries.  Looking back at this comment it indeed does not make any sense and is clear why the results were what they were.  I'll own up to that lol.

On a side note, keep up the great work on this library.
