### ISSUE TITLE
global.Buffer is not a constructor for $base64encode

### ISSUE THREAD

**Issue by peterbroadhurst** [jsonata-js/jsonata#61]
Changes in https://github.com/jsonata-js/jsonata/pull/51 seem to have resulted in:
![image](https://user-images.githubusercontent.com/6660217/27321960-337f84a0-5594-11e7-83ee-414c47015216.png)

Need to have another think about how to do Browser and Node.js safe btoa in a way that continues to work in the browser, but doesn't cause the browserify issues.

**Comment by andrew-coleman** [comment]
When run in the browser, it should be using the built in btoa and atob functions in the global window object.  However, there was no `window.` prefix, so it was attempting to run the code intended for node.js.  Adding the `global` prefix fixes this in the browser, and is node.js safe.
Now fixed in master.
