### ISSUE TITLE
Unable to filter all matching predicate values based on the existing context

### ISSUE THREAD

**Issue by raj-work** [jsonata-js/jsonata#68]
Hi,
We are trying to filter all matching predicate based on the current context value. 
for e.g.
Phone[number=$[0].number] . The expectation is to have number filtered by the 0th index value.
But when i try this, i am getting all Phone objects. Nothing seems to be filtered. Is this the expected behavior? 
Thanks.

**Comment by mattbaileyuk** [comment]
It can certainly be achieved with
`Phone[number=$$.Phone[0]. number]`
but I'll expect @andrew-coleman will come back with a better solution and/or why what you tried didn't work... 🙂

**Comment by andrew-coleman** [comment]
The reason is that `$` is the context value, which within a filter `[...]` is the current iteration of the object within the `Phone` array.  The `$$` is the root of the JSON input data which allows you reference parts of the data outside of the current context.
See http://docs.jsonata.org/programming.html#built-in-variables (sorry about the lack of examples - docs need more work!)

**Comment by raj-work** [comment]
@andrew-coleman @mattbaileyuk -thanks for your valuable inputs. This condition works. One thought on these type of conditions, is there any performance overhead?

**Comment by andrew-coleman** [comment]
@raj-work I'm not aware of performance concerns with this type of expression.  Let us know if you find an issue.  Many thanks.
