### ISSUE TITLE
Simple assignment not working (I must not understand...)

### ISSUE THREAD

**Issue by wnm3** [jsonata-js/jsonata#95]
Given input like:
````
{
  "msg": {
    "payload": {
      "originalInput":"",
      "input": {
        "text": "get weather for jfk"
      }
    }
  }
}
````
and a rule using J:branch 1.4
msg~>|payload|{"originalInput":(msg.payload.input)}|

I expected:
````
{
  "payload": {
    "originalInput":{
      "text": "get weather for jfk"
    },
    "input": {
      "text": "get weather for jfk"
    }
  }
}
````
but got:
````
{
  "payload": {
    "originalInput": "",
    "input": {
      "text": "get weather for jfk"
    }
  }
}
````
even though (msg.payload.input) evaluates to:
````
{
      "text": "get weather for jfk"
}
````
If instead, I use msg~>|payload|{"originalInput":"junk"}| then it gets updated

**Comment by wnm3** [comment]
I see, I forgot that the transform part is in the context of the target so I needed to do:
msg~>|payload|{"originalInput":(input)}|

**Comment by wnm3** [comment]
How would I reference some other part of the json in the transform clause?
For example, if I have:
````
{
  "msg":{
    "payload":{
      "entity":"junk",
      "context":{
        "display_type":{}
      }
    }
  }
}
````
and I wanted to set the msg.payload.context.display_type to the value of msg.payload.entity

I am trying:
msg~>|payload.context.display_type|(msg.payload.entity)|
and even though (msg.payload.entity) resolves to "junk" the display_type remains {}

I think I need a way to reference anything in the transform clause but am not sure how to do this.

**Comment by cray74** [comment]
Try addin "$$" in front of msg.payload.entity (to get to the root context):

(
$ ~> |msg.payload.context|{"display_type": $$.msg.payload.entity}|;
)

See http://try.jsonata.org/H1-5P8Dkf

**Comment by wnm3** [comment]
Based on a solution from here: 
https://github.com/jsonata-js/jsonata/issues/70#issuecomment-343699068

It seems by creating a variable, once can then reference that variable in the transform clause.

However, I think the expectation is the transform clause is an object, not a simple string or number. The following does work, but I'd prefer not to have to assign the variable:
````
(
$entityVal := {"display_type":(msg.payload.entity)};
msg~>|payload.context|$entityVal|
)
````
For example, this does not work:
msg~>|payload.context|{"display_type":(msg.payload.entity)}|

**Comment by wnm3** [comment]
Thanks @cray74 that works perfectly

**Comment by wnm3** [comment]
Thanks @cray74 -- that works if I create the object in the clause.

Is there any way to allow the transform clause to evaluate to a simple type (string, int...) and still allow assignment to the transform target? or must we always reference an object?

**Comment by cray74** [comment]
try wrapping your target in $string('your string'), or $number(9999) or any other function (actually returning an object, if I'm not mistaken).

I'm a total noob btw, so I might be totally off (but I've spent a few hours last weekend with very similar challenges, see http://try.jsonata.org/SkrU3nByf).

**Comment by shrickus** [comment]
According to the new documentation, the update expression (your "display_type") must evaluate to an object -- and it is evaluated relative to the location object or array (your "payload.context"). Since there is no way to reference parent objects, the "entity" expression needs the "$$." prefix, to be referenced starting at the root of the incoming data.

So this expression seems to work for me:
`msg~>| payload.context | { "display_type": $$.msg.payload.entity } |`
which in human-readable form is
> return a transformed "msg" object, updating the "payload.context" object to have a "display_type" property value copied from the "msg.payload.entity" field

I don't understand why, but it's clear that Andrew does not expect the update expression to return a simple type (string, number, boolean). I can imagine that by requiring an object to be returned, the $merge() function logic can be used on the results. But if the update returns a string, why not just replace the location's value instead of trying to merge it?

I think this syntax describes the intent of the change more precisely, and in fewer characters:
`msg~>| payload.context.display_type | $$.msg.payload.entity |`

Unfortunately, using the branch 1.4 implementation, this syntax returns the error:
> The insert/update clause of the transform expression must evaluate to an object: "junk"

**Comment by andrew-coleman** [comment]
The reason this only works at the object level is because it needs a reference to the thing it is going to update.  Take the following example:
```javascript
{
  "msg": {
    "payload": {
      "originalInput":"oldValue",
      "input": {
        "text": "get weather for jfk"
      }
    }
  }
}
```
If the expression was:
`msg ~> | payload.originalInput | 'newValue' |`
the processor would evaluate the expression `payload.originalInput` and get the string `"oldValue"`.   Not a pointer to that string; just the string value.  It will have lost the reference to the object that contained that value.  So we need to specify that the object we want to modify is `payload`, and the updates that we want to make to that object is specified by the next part of the expression.  I can't think of a way round this at the moment.  It's a similar situation to the discussion, and [my response](https://github.com/jsonata-js/jsonata/issues/83#issuecomment-340417807) in issue #83.

**Comment by andrew-coleman** [comment]
I believe this is resolved as per last comment.  Please re-open if not.
